catch failed oauth callbacks
this fixes an edge case - if you register a regular user account with 'a@b.com', and then later try to sign in with the same email using an oauth provider, setRefreshToken will throw because of the db error:
ERROR:  duplicate key value violates unique constraint "accounts_email_key"

this causes the oauth flow to hang and eventually time out.

Instead, we should just redirect to the failure URI for now